services:
  - type: web
    name: store-fe
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        sync: false
      - key: VITE_MEDIA_BASE_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
